CREATE TABLE account_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(30)  NOT NULL UNIQUE,
    kind        VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT account_groups_kind_check CHECK (kind IN ('CREDIT_CARD', 'DEBIT_CARD', 'GENERAL'))
);

CREATE TABLE accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_group_id    BIGINT         NOT NULL,
    name                VARCHAR(50)    NOT NULL,
    ownership           VARCHAR(20)    NOT NULL,
    balance             NUMERIC(19, 2) NOT NULL,
    currency            VARCHAR(3)     NOT NULL,
    exclude_from_stats  BOOLEAN        NOT NULL,
    created_at          TIMESTAMP(6)   NOT NULL,
    updated_at          TIMESTAMP(6)   NOT NULL,
    CONSTRAINT accounts_ownership_check  CHECK (ownership IN ('PERSONAL', 'SHARED')),
    CONSTRAINT fk_accounts_account_group FOREIGN KEY (account_group_id) REFERENCES account_groups(id)
);

CREATE INDEX idx_accounts_account_group_id ON accounts (account_group_id);
