CREATE TABLE category_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(20)  NOT NULL UNIQUE,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT category_groups_name_check CHECK (name IN ('INCOME', 'EXPENSE', 'TRANSFER'))
);

INSERT INTO category_groups (name, created_at, updated_at) VALUES
    ('INCOME',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EXPENSE',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TRANSFER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE categories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_group_id   BIGINT       NOT NULL,
    name                VARCHAR(30)  NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_categories_group       FOREIGN KEY (category_group_id) REFERENCES category_groups(id),
    CONSTRAINT uq_categories_group_name  UNIQUE (category_group_id, name)
);

CREATE INDEX idx_categories_category_group_id ON categories (category_group_id);

CREATE TABLE subcategories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL,
    name        VARCHAR(30)  NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_subcategories_category      FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT uq_subcategories_category_name UNIQUE (category_id, name)
);

CREATE INDEX idx_subcategories_category_id ON subcategories (category_id);

CREATE TABLE entries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_group_id   BIGINT          NOT NULL,
    category_id         BIGINT,
    subcategory_id      BIGINT,
    amount              NUMERIC(19, 2)  NOT NULL,
    transaction_at      TIMESTAMP(6)    NOT NULL,
    from_account_id     BIGINT,
    to_account_id       BIGINT,
    memo                VARCHAR(200),
    created_at          TIMESTAMP(6)    NOT NULL,
    updated_at          TIMESTAMP(6)    NOT NULL,
    CONSTRAINT fk_entries_category_group FOREIGN KEY (category_group_id) REFERENCES category_groups(id),
    CONSTRAINT fk_entries_category       FOREIGN KEY (category_id)       REFERENCES categories(id),
    CONSTRAINT fk_entries_subcategory    FOREIGN KEY (subcategory_id)    REFERENCES subcategories(id),
    CONSTRAINT fk_entries_from_account   FOREIGN KEY (from_account_id)   REFERENCES accounts(id),
    CONSTRAINT fk_entries_to_account     FOREIGN KEY (to_account_id)     REFERENCES accounts(id)
);

CREATE INDEX idx_entries_transaction_at    ON entries (transaction_at);
CREATE INDEX idx_entries_category_group_id ON entries (category_group_id);
CREATE INDEX idx_entries_category_id       ON entries (category_id);
CREATE INDEX idx_entries_from_account_id   ON entries (from_account_id);
CREATE INDEX idx_entries_to_account_id     ON entries (to_account_id);
